version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "

  - package-ecosystem: pip
    directory: /tests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "

  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "

  - package-ecosystem: docker
    directory: /manager
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Ci: "