# This is used by the action https://github.com/dorny/paths-filter

ubuntu_build: &ubuntu_build
  - .github/workflows/base_build.yml
  - '**'

linux_gtest: &linux_gtest
  - .github/workflows/ubuntu_build_with_gtest.yml
  - '.github/workflows/upl*'
  - 'patches/ice_drv/**'
  - '*src'
  - '*build'

ice_build: &ice_build
  - .github/workflows/base_build.yml
  - 'paths/ice_drv/**'
  - 'script/build_ice_driver.sh'

manager_build: &manager_build
  - .github/workflows/base_build.yml
  - 'manager/**'

plugin_build: &plugin_build
  - .github/workflows/base_build.yml
  - 'plugins/**'

rust_build: &rust_hooks_build
  - .github/workflows/base_build.yml
  - 'rust/**'

python_build: &python_hooks_build
  - .github/workflows/base_build.yml
  - 'python/**'

tools_monitors_build: &mtl_monitors_build
  - .github/workflows/base_build.yml
  - 'tools/ebpf/**'

tools_readcap_build: &mtl_readcap_build
  - .github/workflows/base_build.yml
  - 'tools/readcap/**'

tools_cpu_emulator_build: &mtl_cpu_emulator_build
  - .github/workflows/base_build.yml
  - 'tools/sch_smi_emulate/**'
