# This is used by the action https://github.com/dorny/paths-filter

src: &src
  - 'include/**'
  - 'lib/**'
  - 'ld_preload/**'
  - 'patches/dpdk/**'
  - 'tests/**'

build: &build
  - build.sh
  - kahawai.json
  - meson.build
  - meson_options.txt
  - VERSION

workflow_windows: &workflow_windows
  - .github/workflows/windows_build_with_gtest.yml

workflow_linux: &workflow_linux
  - .github/workflows/ubuntu_build_with_gtest.yml
  - '.github/workflows/upl*'

api: &api
  - 'include/**'

ffmpeg_plugin: &ffmpeg_plugin
  - 'ecosystem/ffmpeg_plugin/**'
  - .github/workflows/ffmpeg_plugin.yml

librist: &librist
  - 'ecosystem/librist/**'
  - .github/workflows/rist.yml

obs_plugin: &obs_plugin
  - 'ecosystem/obs_mtl/**'
  - .github/workflows/obs.yml
