# This is used by the action https://github.com/dorny/paths-filter

src: &src
  - 'include/**'
  - 'lib/**'
  - 'ld_preload/**'
  - 'patches/dpdk/**'
  - 'tests/src/**'
  - tests/meson.build
  - tests/meson_options.txt
  - 'manager/**'

app_src: &app_src
  - 'app/**'

build: &build
  - build.sh
  - kahawai.json
  - meson.build
  - meson_options.txt
  - .github/workflows/ubuntu_build.yml
  - VERSION

windows_gtest: &windows_gtest
  - .github/workflows/windows_build_with_gtest.yml
  - *src
  - *build

linux_gtest: &linux_gtest
  - .github/workflows/ubuntu_build_with_gtest.yml
  - '.github/workflows/upl*'
  - 'patches/ice_drv/**'
  - *src
  - *build

api: &api
  - 'include/**'

ffmpeg_plugin: &ffmpeg_plugin
  - *api
  - 'ecosystem/ffmpeg_plugin/**'
  - .github/workflows/ffmpeg_plugin.yml

ecosystem: &ecosystem
  - *api
  - .github/workflows/ecosystem.yml
  - 'ecosystem/obs_mtl/**'
  - "ecosystem/librist/**"

dpdk_patches: &dpdk_patches
  - 'patches/dpdk/**'
  - .github/workflows/dpdk_patches_build.yml

centos_build: &centos_build
  - .github/workflows/centos_build.yml
  - *src
  - *build
  - *app_src

ubuntu_build: &ubuntu_build
  - .github/workflows/ubuntu_build.yml
  - *src
  - *build
  - *app_src

clang_build: &clang_build
  - .github/workflows/clang_build.yml
  - *src
  - *build
  - *app_src

msys2_build: &msys2_build
  - .github/workflows/msys2_build.yml
  - *src
  - *build

afxdp_build: &afxdp_build
  - .github/workflows/afxdp_build.yml
  - script/build_ebpf_xdp.sh
  - *src
  - *build

afxdp_test: &afxdp_test
  - .github/workflows/afxdp_build_with_gtest.yml
  - *src
  - *build

tools_build: &tools_build
  - 'tools/**'
