#!/bin/bash
git clean -xdf script
rm -rf build
rm /usr/local/share/dpdk/telemetry-endpoints/memory.py
rm /usr/local/share/dpdk/telemetry-endpoints/cpu.py
rm /usr/local/share/dpdk/telemetry-endpoints/counters.py
rm /usr/local/share/dpdk/examples/vhost_crypto/Makefile
rm /usr/local/share/dpdk/examples/vhost_crypto/main.c
rm /usr/local/share/dpdk/examples/ptpclient/ptpclient.c
rm /usr/local/share/dpdk/examples/ptpclient/Makefile
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_gcm.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_sha.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_hmac.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_dev_self_test.h
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_cmac.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_dev_self_test.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_xts.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_tdes.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_eddsa.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation.h
rm /usr/local/share/dpdk/examples/fips_validation/Makefile
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_rsa.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_ccm.c
rm /usr/local/share/dpdk/examples/fips_validation/main.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_aes.c
rm /usr/local/share/dpdk/examples/fips_validation/fips_validation_ecdsa.c
rm /usr/local/share/dpdk/examples/ip_reassembly/Makefile
rm /usr/local/share/dpdk/examples/ip_reassembly/main.c
rm /usr/local/share/dpdk/examples/eventdev_pipeline/pipeline_worker_generic.c
rm /usr/local/share/dpdk/examples/eventdev_pipeline/pipeline_worker_tx.c
rm /usr/local/share/dpdk/examples/eventdev_pipeline/pipeline_common.h
rm /usr/local/share/dpdk/examples/eventdev_pipeline/Makefile
rm /usr/local/share/dpdk/examples/eventdev_pipeline/main.c
rm /usr/local/share/dpdk/examples/ip_fragmentation/Makefile
rm /usr/local/share/dpdk/examples/ip_fragmentation/main.c
rm /usr/local/share/dpdk/examples/distributor/Makefile
rm /usr/local/share/dpdk/examples/distributor/main.c
rm /usr/local/share/dpdk/examples/vmdq/Makefile
rm /usr/local/share/dpdk/examples/vmdq/main.c
rm /usr/local/share/dpdk/examples/l3fwd-power/perf_core.h
rm /usr/local/share/dpdk/examples/l3fwd-power/perf_core.c
rm /usr/local/share/dpdk/examples/l3fwd-power/Makefile
rm /usr/local/share/dpdk/examples/l3fwd-power/main.h
rm /usr/local/share/dpdk/examples/l3fwd-power/main.c
rm /usr/local/share/dpdk/examples/l2fwd-crypto/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-crypto/main.c
rm /usr/local/share/dpdk/examples/vmdq_dcb/Makefile
rm /usr/local/share/dpdk/examples/vmdq_dcb/main.c
rm /usr/local/share/dpdk/examples/multi_process/Makefile
rm /usr/local/share/dpdk/examples/multi_process/hotplug_mp/commands.list
rm /usr/local/share/dpdk/examples/multi_process/hotplug_mp/commands.c
rm /usr/local/share/dpdk/examples/multi_process/hotplug_mp/Makefile
rm /usr/local/share/dpdk/examples/multi_process/hotplug_mp/main.c
rm /usr/local/share/dpdk/examples/multi_process/simple_mp/commands.list
rm /usr/local/share/dpdk/examples/multi_process/simple_mp/Makefile
rm /usr/local/share/dpdk/examples/multi_process/simple_mp/mp_commands.h
rm /usr/local/share/dpdk/examples/multi_process/simple_mp/mp_commands.c
rm /usr/local/share/dpdk/examples/multi_process/simple_mp/main.c
rm /usr/local/share/dpdk/examples/multi_process/symmetric_mp/Makefile
rm /usr/local/share/dpdk/examples/multi_process/symmetric_mp/main.c
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/Makefile
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/init.h
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/args.c
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/Makefile
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/init.c
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/main.c
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_server/args.h
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/shared/common.h
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_client/Makefile
rm /usr/local/share/dpdk/examples/multi_process/client_server_mp/mp_client/client.c
rm /usr/local/share/dpdk/examples/ethtool/Makefile
rm /usr/local/share/dpdk/examples/ethtool/ethtool-app/ethapp.c
rm /usr/local/share/dpdk/examples/ethtool/ethtool-app/Makefile
rm /usr/local/share/dpdk/examples/ethtool/ethtool-app/ethapp.h
rm /usr/local/share/dpdk/examples/ethtool/ethtool-app/main.c
rm /usr/local/share/dpdk/examples/ethtool/lib/Makefile
rm /usr/local/share/dpdk/examples/ethtool/lib/rte_ethtool.c
rm /usr/local/share/dpdk/examples/ethtool/lib/rte_ethtool.h
rm /usr/local/share/dpdk/examples/skeleton/basicfwd.c
rm /usr/local/share/dpdk/examples/skeleton/Makefile
rm /usr/local/share/dpdk/examples/bbdev_app/Makefile
rm /usr/local/share/dpdk/examples/bbdev_app/main.c
rm /usr/local/share/dpdk/examples/timer/Makefile
rm /usr/local/share/dpdk/examples/timer/main.c
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_common.h
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_poll.h
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_common.c
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_event.c
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_event.h
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_event_generic.c
rm /usr/local/share/dpdk/examples/l2fwd-event/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_poll.c
rm /usr/local/share/dpdk/examples/l2fwd-event/l2fwd_event_internal_port.c
rm /usr/local/share/dpdk/examples/l2fwd-event/main.c
rm /usr/local/share/dpdk/examples/qos_sched/app_thread.c
rm /usr/local/share/dpdk/examples/qos_sched/cfg_file.h
rm /usr/local/share/dpdk/examples/qos_sched/cfg_file.c
rm /usr/local/share/dpdk/examples/qos_sched/args.c
rm /usr/local/share/dpdk/examples/qos_sched/profile_red.cfg
rm /usr/local/share/dpdk/examples/qos_sched/cmdline.c
rm /usr/local/share/dpdk/examples/qos_sched/Makefile
rm /usr/local/share/dpdk/examples/qos_sched/main.h
rm /usr/local/share/dpdk/examples/qos_sched/stats.c
rm /usr/local/share/dpdk/examples/qos_sched/profile_ov.cfg
rm /usr/local/share/dpdk/examples/qos_sched/init.c
rm /usr/local/share/dpdk/examples/qos_sched/profile.cfg
rm /usr/local/share/dpdk/examples/qos_sched/profile_pie.cfg
rm /usr/local/share/dpdk/examples/qos_sched/main.c
rm /usr/local/share/dpdk/examples/pipeline/cli.c
rm /usr/local/share/dpdk/examples/pipeline/cli.h
rm /usr/local/share/dpdk/examples/pipeline/obj.c
rm /usr/local/share/dpdk/examples/pipeline/Makefile
rm /usr/local/share/dpdk/examples/pipeline/thread.h
rm /usr/local/share/dpdk/examples/pipeline/conn.c
rm /usr/local/share/dpdk/examples/pipeline/obj.h
rm /usr/local/share/dpdk/examples/pipeline/thread.c
rm /usr/local/share/dpdk/examples/pipeline/conn.h
rm /usr/local/share/dpdk/examples/pipeline/main.c
rm /usr/local/share/dpdk/examples/pipeline/examples/varbit.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/pcap.io
rm /usr/local/share/dpdk/examples/pipeline/examples/mirroring.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/rss.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/ethdev.io
rm /usr/local/share/dpdk/examples/pipeline/examples/fib_nexthop_group_table.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/ipv6_addr_swap.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/packet.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/hash_func.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/vxlan.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/registers.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/ipsec_sa.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/fib.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/fib_nexthop_table.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/vxlan.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/hash_func.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/fib_routing_table.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/rss.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/fib.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/meter.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/registers.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/learner.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/ipsec.io
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd_macswp_pcap.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/ipv6_addr_swap.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/recirculation.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/mirroring.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/ipsec.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/vxlan_table.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd_pcap.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/selector.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/meter.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/recirculation.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/selector.txt
rm /usr/local/share/dpdk/examples/pipeline/examples/varbit.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/selector.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd_macswp.spec
rm /usr/local/share/dpdk/examples/pipeline/examples/vxlan_table.py
rm /usr/local/share/dpdk/examples/pipeline/examples/l2fwd_macswp.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/learner.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/ipsec.cli
rm /usr/local/share/dpdk/examples/pipeline/examples/vxlan_pcap.cli
rm /usr/local/share/dpdk/examples/qos_meter/rte_policer.c
rm /usr/local/share/dpdk/examples/qos_meter/rte_policer.h
rm /usr/local/share/dpdk/examples/qos_meter/Makefile
rm /usr/local/share/dpdk/examples/qos_meter/main.h
rm /usr/local/share/dpdk/examples/qos_meter/main.c
rm /usr/local/share/dpdk/examples/packet_ordering/Makefile
rm /usr/local/share/dpdk/examples/packet_ordering/main.c
rm /usr/local/share/dpdk/examples/ntb/commands.list
rm /usr/local/share/dpdk/examples/ntb/ntb_fwd.c
rm /usr/local/share/dpdk/examples/ntb/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-macsec/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-macsec/main.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_lpm.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_acl.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_acl_scalar.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_lpm.h
rm /usr/local/share/dpdk/examples/l3fwd/lpm_default_v4.cfg
rm /usr/local/share/dpdk/examples/l3fwd/em_default_v4.cfg
rm /usr/local/share/dpdk/examples/l3fwd/em_default_v6.cfg
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_event.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_event_internal_port.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em_hlm_neon.h
rm /usr/local/share/dpdk/examples/l3fwd/lpm_default_v6.cfg
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_route.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_altivec.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em_hlm.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_acl.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_neon.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em_hlm_sse.h
rm /usr/local/share/dpdk/examples/l3fwd/Makefile
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_lpm_altivec.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_common.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_em_sequential.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_event_generic.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_event.c
rm /usr/local/share/dpdk/examples/l3fwd/em_route_parse.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_lpm_neon.h
rm /usr/local/share/dpdk/examples/l3fwd/lpm_route_parse.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_sse.h
rm /usr/local/share/dpdk/examples/l3fwd/main.c
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_lpm_sse.h
rm /usr/local/share/dpdk/examples/l3fwd/l3fwd_fib.c
rm /usr/local/share/dpdk/examples/flow_filtering/flow_skeleton.c
rm /usr/local/share/dpdk/examples/flow_filtering/jump_flow.c
rm /usr/local/share/dpdk/examples/flow_filtering/Makefile
rm /usr/local/share/dpdk/examples/flow_filtering/jump_flow.h
rm /usr/local/share/dpdk/examples/flow_filtering/main.c
rm /usr/local/share/dpdk/examples/flow_filtering/common.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_port_affinity.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_roce_ib_bth.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_nsh.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_roce_ib_bth.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_switch_granularity.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_gre.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_ipv4.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_ipv4.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_gre.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_re_route_to_kernel.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_mpls.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_nsh.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_port_affinity.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_match_mpls.c
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_re_route_to_kernel.h
rm /usr/local/share/dpdk/examples/flow_filtering/snippets/snippet_switch_granularity.c
rm /usr/local/share/dpdk/examples/helloworld/Makefile
rm /usr/local/share/dpdk/examples/helloworld/main.c
rm /usr/local/share/dpdk/examples/l2fwd-jobstats/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-jobstats/main.c
rm /usr/local/share/dpdk/examples/bpf/README
rm /usr/local/share/dpdk/examples/bpf/dummy.c
rm /usr/local/share/dpdk/examples/bpf/t1.c
rm /usr/local/share/dpdk/examples/bpf/t2.c
rm /usr/local/share/dpdk/examples/bpf/t3.c
rm /usr/local/share/dpdk/examples/vdpa/commands.list
rm /usr/local/share/dpdk/examples/vdpa/Makefile
rm /usr/local/share/dpdk/examples/vdpa/main.c
rm /usr/local/share/dpdk/examples/vdpa/vdpa_blk_compact.h
rm /usr/local/share/dpdk/examples/ipv4_multicast/Makefile
rm /usr/local/share/dpdk/examples/ipv4_multicast/main.c
rm /usr/local/share/dpdk/examples/rxtx_callbacks/Makefile
rm /usr/local/share/dpdk/examples/rxtx_callbacks/main.c
rm /usr/local/share/dpdk/examples/common/pkt_group.h
rm /usr/local/share/dpdk/examples/common/sse/port_group.h
rm /usr/local/share/dpdk/examples/common/altivec/port_group.h
rm /usr/local/share/dpdk/examples/common/neon/port_group.h
rm /usr/local/share/dpdk/examples/bond/commands.list
rm /usr/local/share/dpdk/examples/bond/Makefile
rm /usr/local/share/dpdk/examples/bond/main.c
rm /usr/local/share/dpdk/examples/l3fwd-graph/Makefile
rm /usr/local/share/dpdk/examples/l3fwd-graph/main.c
rm /usr/local/share/dpdk/examples/l2fwd-cat/cat.c
rm /usr/local/share/dpdk/examples/l2fwd-cat/cat.h
rm /usr/local/share/dpdk/examples/l2fwd-cat/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-cat/l2fwd-cat.c
rm /usr/local/share/dpdk/examples/server_node_efd/Makefile
rm /usr/local/share/dpdk/examples/server_node_efd/shared/common.h
rm /usr/local/share/dpdk/examples/server_node_efd/efd_node/node.c
rm /usr/local/share/dpdk/examples/server_node_efd/efd_node/Makefile
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/init.h
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/args.c
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/Makefile
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/init.c
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/main.c
rm /usr/local/share/dpdk/examples/server_node_efd/efd_server/args.h
rm /usr/local/share/dpdk/examples/vhost/Makefile
rm /usr/local/share/dpdk/examples/vhost/main.h
rm /usr/local/share/dpdk/examples/vhost/main.c
rm /usr/local/share/dpdk/examples/vhost/virtio_net.c
rm /usr/local/share/dpdk/examples/ip_pipeline/action.c
rm /usr/local/share/dpdk/examples/ip_pipeline/swq.h
rm /usr/local/share/dpdk/examples/ip_pipeline/pipeline.h
rm /usr/local/share/dpdk/examples/ip_pipeline/link.h
rm /usr/local/share/dpdk/examples/ip_pipeline/tmgr.c
rm /usr/local/share/dpdk/examples/ip_pipeline/cli.c
rm /usr/local/share/dpdk/examples/ip_pipeline/cli.h
rm /usr/local/share/dpdk/examples/ip_pipeline/tap.c
rm /usr/local/share/dpdk/examples/ip_pipeline/mempool.c
rm /usr/local/share/dpdk/examples/ip_pipeline/parser.c
rm /usr/local/share/dpdk/examples/ip_pipeline/mempool.h
rm /usr/local/share/dpdk/examples/ip_pipeline/cryptodev.c
rm /usr/local/share/dpdk/examples/ip_pipeline/tmgr.h
rm /usr/local/share/dpdk/examples/ip_pipeline/Makefile
rm /usr/local/share/dpdk/examples/ip_pipeline/swq.c
rm /usr/local/share/dpdk/examples/ip_pipeline/thread.h
rm /usr/local/share/dpdk/examples/ip_pipeline/conn.c
rm /usr/local/share/dpdk/examples/ip_pipeline/cryptodev.h
rm /usr/local/share/dpdk/examples/ip_pipeline/thread.c
rm /usr/local/share/dpdk/examples/ip_pipeline/tap.h
rm /usr/local/share/dpdk/examples/ip_pipeline/parser.h
rm /usr/local/share/dpdk/examples/ip_pipeline/link.c
rm /usr/local/share/dpdk/examples/ip_pipeline/conn.h
rm /usr/local/share/dpdk/examples/ip_pipeline/main.c
rm /usr/local/share/dpdk/examples/ip_pipeline/action.h
rm /usr/local/share/dpdk/examples/ip_pipeline/pipeline.c
rm /usr/local/share/dpdk/examples/ip_pipeline/common.h
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/route_ecmp.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/tap.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/l2fwd.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/rss.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/flow_crypto.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/route.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/flow.cli
rm /usr/local/share/dpdk/examples/ip_pipeline/examples/firewall.cli
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec-secgw.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipip.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/esp.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/ep0.cfg
rm /usr/local/share/dpdk/examples/ipsec-secgw/event_helper.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/event_helper.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/sp4.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/sad.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/parser.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec_process.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec_lpm_neon.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/flow.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/rt.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/Makefile
rm /usr/local/share/dpdk/examples/ipsec-secgw/flow.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec_worker.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/sa.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/sad.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/parser.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/ep1.cfg
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec_worker.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/sp6.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec_neon.h
rm /usr/local/share/dpdk/examples/ipsec-secgw/esp.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/ipsec-secgw.c
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_null_header_reconstruct.py
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aescbc_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_3descbc_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/run_test.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/bypass_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aescbc_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aesgcm_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/pkttest.py
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/linux_test.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_3descbc_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/common_defs_secgw.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aesgcm_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aescbc_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/pkttest.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aescbc_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aesctr_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aesgcm_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_ipv6opts.py
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aesctr_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/load_env.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/data_rxtx.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_3descbc_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_3descbc_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/trs_aesctr_sha1_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aesctr_sha1_common_defs.sh
rm /usr/local/share/dpdk/examples/ipsec-secgw/test/tun_aesgcm_common_defs.sh
rm /usr/local/share/dpdk/examples/l2fwd/Makefile
rm /usr/local/share/dpdk/examples/l2fwd/main.c
rm /usr/local/share/dpdk/examples/dma/Makefile
rm /usr/local/share/dpdk/examples/dma/dmafwd.c
rm /usr/local/share/dpdk/examples/cmdline/parse_obj_list.h
rm /usr/local/share/dpdk/examples/cmdline/commands.h
rm /usr/local/share/dpdk/examples/cmdline/parse_obj_list.c
rm /usr/local/share/dpdk/examples/cmdline/commands.c
rm /usr/local/share/dpdk/examples/cmdline/Makefile
rm /usr/local/share/dpdk/examples/cmdline/main.c
rm /usr/local/share/dpdk/examples/vm_power_manager/parse.c
rm /usr/local/share/dpdk/examples/vm_power_manager/vm_power_cli.c
rm /usr/local/share/dpdk/examples/vm_power_manager/parse.h
rm /usr/local/share/dpdk/examples/vm_power_manager/channel_manager.c
rm /usr/local/share/dpdk/examples/vm_power_manager/power_manager.c
rm /usr/local/share/dpdk/examples/vm_power_manager/oob_monitor_nop.c
rm /usr/local/share/dpdk/examples/vm_power_manager/oob_monitor.h
rm /usr/local/share/dpdk/examples/vm_power_manager/vm_power_cli.h
rm /usr/local/share/dpdk/examples/vm_power_manager/Makefile
rm /usr/local/share/dpdk/examples/vm_power_manager/channel_manager.h
rm /usr/local/share/dpdk/examples/vm_power_manager/oob_monitor_x86.c
rm /usr/local/share/dpdk/examples/vm_power_manager/power_manager.h
rm /usr/local/share/dpdk/examples/vm_power_manager/channel_monitor.c
rm /usr/local/share/dpdk/examples/vm_power_manager/channel_monitor.h
rm /usr/local/share/dpdk/examples/vm_power_manager/main.c
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/parse.c
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/parse.h
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/Makefile
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/vm_power_cli_guest.c
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/vm_power_cli_guest.h
rm /usr/local/share/dpdk/examples/vm_power_manager/guest_cli/main.c
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/shm.c
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/shm.h
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/main.c
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/ka-agent/Makefile
rm /usr/local/share/dpdk/examples/l2fwd-keepalive/ka-agent/main.c
rm /usr/local/share/dpdk/examples/service_cores/Makefile
rm /usr/local/share/dpdk/examples/service_cores/main.c
rm /usr/local/share/dpdk/examples/link_status_interrupt/Makefile
rm /usr/local/share/dpdk/examples/link_status_interrupt/main.c
rm /usr/local/share/dpdk/examples/vhost_blk/vhost_blk.h
rm /usr/local/share/dpdk/examples/vhost_blk/vhost_blk_compat.c
rm /usr/local/share/dpdk/examples/vhost_blk/Makefile
rm /usr/local/share/dpdk/examples/vhost_blk/blk.c
rm /usr/local/share/dpdk/examples/vhost_blk/vhost_blk.c
rm /usr/local/share/dpdk/examples/vhost_blk/blk_spec.h
rm /usr/local/lib/x86_64-linux-gnu/librte_log.a
rm /usr/local/lib/x86_64-linux-gnu/librte_log.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_log.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_log.so
rm /usr/local/lib/x86_64-linux-gnu/librte_kvargs.a
rm /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_kvargs.so
rm /usr/local/lib/x86_64-linux-gnu/librte_argparse.a
rm /usr/local/lib/x86_64-linux-gnu/librte_argparse.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_argparse.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_argparse.so
rm /usr/local/lib/x86_64-linux-gnu/librte_telemetry.a
rm /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_telemetry.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pmu.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pmu.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pmu.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pmu.so
rm /usr/local/lib/x86_64-linux-gnu/librte_eal.a
rm /usr/local/lib/x86_64-linux-gnu/librte_eal.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_eal.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_eal.so
rm /usr/local/lib/x86_64-linux-gnu/librte_ring.a
rm /usr/local/lib/x86_64-linux-gnu/librte_ring.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_ring.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_ring.so
rm /usr/local/lib/x86_64-linux-gnu/librte_rcu.a
rm /usr/local/lib/x86_64-linux-gnu/librte_rcu.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_rcu.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_rcu.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool.a
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mbuf.a
rm /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_mbuf.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net.a
rm /usr/local/lib/x86_64-linux-gnu/librte_net.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_net.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_net.so
rm /usr/local/lib/x86_64-linux-gnu/librte_meter.a
rm /usr/local/lib/x86_64-linux-gnu/librte_meter.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_meter.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_meter.so
rm /usr/local/lib/x86_64-linux-gnu/librte_ethdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_ethdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pci.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pci.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pci.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pci.so
rm /usr/local/lib/x86_64-linux-gnu/librte_cmdline.a
rm /usr/local/lib/x86_64-linux-gnu/librte_cmdline.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_cmdline.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_cmdline.so
rm /usr/local/lib/x86_64-linux-gnu/librte_metrics.a
rm /usr/local/lib/x86_64-linux-gnu/librte_metrics.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_metrics.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_metrics.so
rm /usr/local/lib/x86_64-linux-gnu/librte_hash.a
rm /usr/local/lib/x86_64-linux-gnu/librte_hash.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_hash.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_hash.so
rm /usr/local/lib/x86_64-linux-gnu/librte_timer.a
rm /usr/local/lib/x86_64-linux-gnu/librte_timer.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_timer.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_timer.so
rm /usr/local/lib/x86_64-linux-gnu/librte_acl.a
rm /usr/local/lib/x86_64-linux-gnu/librte_acl.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_acl.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_acl.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bbdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_bbdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_bbdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_bbdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bitratestats.a
rm /usr/local/lib/x86_64-linux-gnu/librte_bitratestats.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_bitratestats.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_bitratestats.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bpf.a
rm /usr/local/lib/x86_64-linux-gnu/librte_bpf.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_bpf.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_bpf.so
rm /usr/local/lib/x86_64-linux-gnu/librte_cfgfile.a
rm /usr/local/lib/x86_64-linux-gnu/librte_cfgfile.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_cfgfile.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_cfgfile.so
rm /usr/local/lib/x86_64-linux-gnu/librte_compressdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_compressdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_compressdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_compressdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_cryptodev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_cryptodev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_cryptodev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_cryptodev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_distributor.a
rm /usr/local/lib/x86_64-linux-gnu/librte_distributor.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_distributor.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_distributor.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dmadev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_dmadev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_dmadev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_dmadev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_efd.a
rm /usr/local/lib/x86_64-linux-gnu/librte_efd.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_efd.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_efd.so
rm /usr/local/lib/x86_64-linux-gnu/librte_eventdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_eventdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_eventdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_eventdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dispatcher.a
rm /usr/local/lib/x86_64-linux-gnu/librte_dispatcher.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_dispatcher.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_dispatcher.so
rm /usr/local/lib/x86_64-linux-gnu/librte_gpudev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_gpudev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_gpudev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_gpudev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_gro.a
rm /usr/local/lib/x86_64-linux-gnu/librte_gro.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_gro.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_gro.so
rm /usr/local/lib/x86_64-linux-gnu/librte_gso.a
rm /usr/local/lib/x86_64-linux-gnu/librte_gso.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_gso.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_gso.so
rm /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.a
rm /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_ip_frag.so
rm /usr/local/lib/x86_64-linux-gnu/librte_jobstats.a
rm /usr/local/lib/x86_64-linux-gnu/librte_jobstats.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_jobstats.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_jobstats.so
rm /usr/local/lib/x86_64-linux-gnu/librte_latencystats.a
rm /usr/local/lib/x86_64-linux-gnu/librte_latencystats.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_latencystats.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_latencystats.so
rm /usr/local/lib/x86_64-linux-gnu/librte_lpm.a
rm /usr/local/lib/x86_64-linux-gnu/librte_lpm.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_lpm.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_lpm.so
rm /usr/local/lib/x86_64-linux-gnu/librte_member.a
rm /usr/local/lib/x86_64-linux-gnu/librte_member.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_member.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_member.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pcapng.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pcapng.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pcapng.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pcapng.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power.a
rm /usr/local/lib/x86_64-linux-gnu/librte_power.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_power.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_power.so
rm /usr/local/lib/x86_64-linux-gnu/librte_rawdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_rawdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_rawdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_rawdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_regexdev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_regexdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_regexdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_regexdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mldev.a
rm /usr/local/lib/x86_64-linux-gnu/librte_mldev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_mldev.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_mldev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_rib.a
rm /usr/local/lib/x86_64-linux-gnu/librte_rib.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_rib.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_rib.so
rm /usr/local/lib/x86_64-linux-gnu/librte_reorder.a
rm /usr/local/lib/x86_64-linux-gnu/librte_reorder.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_reorder.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_reorder.so
rm /usr/local/lib/x86_64-linux-gnu/librte_sched.a
rm /usr/local/lib/x86_64-linux-gnu/librte_sched.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_sched.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_sched.so
rm /usr/local/lib/x86_64-linux-gnu/librte_security.a
rm /usr/local/lib/x86_64-linux-gnu/librte_security.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_security.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_security.so
rm /usr/local/lib/x86_64-linux-gnu/librte_stack.a
rm /usr/local/lib/x86_64-linux-gnu/librte_stack.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_stack.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_stack.so
rm /usr/local/lib/x86_64-linux-gnu/librte_vhost.a
rm /usr/local/lib/x86_64-linux-gnu/librte_vhost.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_vhost.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_vhost.so
rm /usr/local/lib/x86_64-linux-gnu/librte_ipsec.a
rm /usr/local/lib/x86_64-linux-gnu/librte_ipsec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_ipsec.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_ipsec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pdcp.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pdcp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pdcp.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pdcp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_fib.a
rm /usr/local/lib/x86_64-linux-gnu/librte_fib.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_fib.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_fib.so
rm /usr/local/lib/x86_64-linux-gnu/librte_port.a
rm /usr/local/lib/x86_64-linux-gnu/librte_port.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_port.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_port.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pdump.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pdump.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pdump.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pdump.so
rm /usr/local/lib/x86_64-linux-gnu/librte_table.a
rm /usr/local/lib/x86_64-linux-gnu/librte_table.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_table.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_table.so
rm /usr/local/lib/x86_64-linux-gnu/librte_pipeline.a
rm /usr/local/lib/x86_64-linux-gnu/librte_pipeline.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_pipeline.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_pipeline.so
rm /usr/local/lib/x86_64-linux-gnu/librte_graph.a
rm /usr/local/lib/x86_64-linux-gnu/librte_graph.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_graph.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_graph.so
rm /usr/local/lib/x86_64-linux-gnu/librte_node.a
rm /usr/local/lib/x86_64-linux-gnu/librte_node.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/librte_node.so.26
rm /usr/local/lib/x86_64-linux-gnu/librte_node.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_cpt.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cpt.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cpt.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cpt.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_dpaax.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_dpaax.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_dpaax.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_dpaax.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_ionic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_ionic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_ionic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_ionic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_auxiliary.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_auxiliary.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_auxiliary.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_auxiliary.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_cdx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_cdx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_cdx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_cdx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_dpaa.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_dpaa.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_dpaa.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_dpaa.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_fslmc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_fslmc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_fslmc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_fslmc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_ifpga.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_ifpga.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_ifpga.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_ifpga.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_pci.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_pci.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_pci.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_pci.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_platform.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_platform.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_platform.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_platform.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_uacce.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_uacce.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_uacce.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_uacce.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_vdev.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vdev.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vdev.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vdev.so
rm /usr/local/lib/x86_64-linux-gnu/librte_bus_vmbus.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vmbus.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vmbus.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_bus_vmbus.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_nfp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nfp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nfp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nfp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_nitrox.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nitrox.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nitrox.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_nitrox.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_qat.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_qat.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_qat.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_qat.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_sfc_efx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_sfc_efx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_sfc_efx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_sfc_efx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_common_zsda.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_zsda.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_zsda.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_common_zsda.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_bucket.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_bucket.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_bucket.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_bucket.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_dpaa.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_dpaa2.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa2.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa2.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_dpaa2.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_ring.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_ring.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_ring.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_ring.so
rm /usr/local/lib/x86_64-linux-gnu/librte_mempool_stack.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_stack.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_stack.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_mempool_stack.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_dpaa.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_dpaa2.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa2.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa2.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_dpaa2.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_hisi_acc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_acc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_acc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_acc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_hisi_pciep.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_pciep.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_pciep.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_hisi_pciep.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_idxd.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_idxd.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_idxd.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_idxd.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_ioat.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_ioat.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_ioat.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_ioat.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_odm.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_odm.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_odm.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_odm.so
rm /usr/local/lib/x86_64-linux-gnu/librte_dma_skeleton.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_skeleton.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_skeleton.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_dma_skeleton.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_af_packet.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_af_packet.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_af_packet.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_af_packet.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ark.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ark.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ark.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ark.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_atlantic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_atlantic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_atlantic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_atlantic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_avp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_avp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_avp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_avp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_axgbe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_axgbe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_axgbe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_axgbe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_bnx2x.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnx2x.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnx2x.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnx2x.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_bnxt.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnxt.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnxt.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bnxt.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_bond.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bond.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bond.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_bond.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_cxgbe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cxgbe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cxgbe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cxgbe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_dpaa.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_dpaa2.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa2.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa2.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_dpaa2.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ena.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ena.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ena.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ena.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_enetc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_enetfec.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetfec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetfec.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enetfec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_enic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_enic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_failsafe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_failsafe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_failsafe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_failsafe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_gve.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_gve.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_gve.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_gve.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_hinic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_hinic3.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic3.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic3.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hinic3.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_hns3.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hns3.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hns3.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_hns3.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_e1000.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_e1000.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_e1000.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_e1000.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_fm10k.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_fm10k.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_fm10k.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_fm10k.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_i40e.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_i40e.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_i40e.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_i40e.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_iavf.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_iavf.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_iavf.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_iavf.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ice.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ice.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ice.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ice.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_idpf.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_idpf.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_idpf.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_idpf.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ipn3ke.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ipn3ke.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ipn3ke.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ipn3ke.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ixgbe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ixgbe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ixgbe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ixgbe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_cpfl.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cpfl.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cpfl.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_cpfl.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ionic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ionic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ionic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ionic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_memif.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_memif.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_memif.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_memif.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_mlx4.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx4.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx4.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx4.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_nbl.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nbl.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nbl.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nbl.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_netvsc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_netvsc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_netvsc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_netvsc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_nfp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nfp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nfp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_nfp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ngbe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ngbe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ngbe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ngbe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ntnic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ntnic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ntnic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ntnic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_null.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_null.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_null.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_null.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_octeon_ep.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeon_ep.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeon_ep.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_octeon_ep.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_pcap.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pcap.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pcap.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pcap.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_pfe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pfe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pfe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_pfe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_qede.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_qede.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_qede.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_qede.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_r8169.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_r8169.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_r8169.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_r8169.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_ring.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ring.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ring.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_ring.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_rnp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_rnp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_rnp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_rnp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_sfc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_sfc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_sfc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_sfc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_softnic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_softnic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_softnic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_softnic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_tap.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_tap.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_tap.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_tap.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_thunderx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_thunderx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_thunderx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_thunderx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_txgbe.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_txgbe.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_txgbe.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_txgbe.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_vdev_netvsc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vdev_netvsc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vdev_netvsc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vdev_netvsc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_vhost.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vhost.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vhost.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vhost.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_virtio.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_virtio.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_virtio.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_virtio.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_vmxnet3.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vmxnet3.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vmxnet3.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_vmxnet3.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_xsc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_xsc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_xsc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_xsc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_net_zxdh.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_zxdh.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_zxdh.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_net_zxdh.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_cnxk_bphy.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_bphy.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_bphy.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_bphy.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_cnxk_gpio.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_gpio.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_gpio.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_gpio.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_cnxk_rvu_lf.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_rvu_lf.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_rvu_lf.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_cnxk_rvu_lf.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_dpaa2_cmdif.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_dpaa2_cmdif.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_dpaa2_cmdif.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_dpaa2_cmdif.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_gdtc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_gdtc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_gdtc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_gdtc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_ifpga.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ifpga.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ifpga.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ifpga.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_ntb.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ntb.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ntb.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_ntb.so
rm /usr/local/lib/x86_64-linux-gnu/librte_raw_skeleton.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_skeleton.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_skeleton.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_raw_skeleton.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_bcmfs.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_bcmfs.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_bcmfs.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_bcmfs.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_caam_jr.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_caam_jr.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_caam_jr.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_caam_jr.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_ccp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ccp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ccp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ccp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_dpaa_sec.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa_sec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa_sec.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa_sec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_dpaa2_sec.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa2_sec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa2_sec.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_dpaa2_sec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_ionic.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ionic.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ionic.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_ionic.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_nitrox.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_nitrox.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_nitrox.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_nitrox.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_null.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_null.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_null.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_null.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_openssl.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_openssl.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_openssl.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_openssl.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_scheduler.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_scheduler.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_scheduler.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_scheduler.so
rm /usr/local/lib/x86_64-linux-gnu/librte_crypto_virtio.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_virtio.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_virtio.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_crypto_virtio.so
rm /usr/local/lib/x86_64-linux-gnu/librte_compress_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_compress_nitrox.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_nitrox.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_nitrox.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_nitrox.so
rm /usr/local/lib/x86_64-linux-gnu/librte_compress_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_compress_zlib.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_zlib.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_zlib.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_compress_zlib.so
rm /usr/local/lib/x86_64-linux-gnu/librte_regex_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_regex_cn9k.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_cn9k.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_cn9k.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_regex_cn9k.so
rm /usr/local/lib/x86_64-linux-gnu/librte_ml_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_ml_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_ml_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_ml_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_vdpa_ifc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_ifc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_ifc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_ifc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_vdpa_mlx5.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_mlx5.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_mlx5.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_mlx5.so
rm /usr/local/lib/x86_64-linux-gnu/librte_vdpa_nfp.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_nfp.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_nfp.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_nfp.so
rm /usr/local/lib/x86_64-linux-gnu/librte_vdpa_sfc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_sfc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_sfc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_vdpa_sfc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_cnxk.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_cnxk.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_cnxk.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_cnxk.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_dlb2.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dlb2.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dlb2.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dlb2.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_dpaa.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_dpaa2.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa2.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa2.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dpaa2.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_dsw.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dsw.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dsw.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_dsw.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_octeontx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_octeontx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_octeontx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_octeontx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_opdl.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_opdl.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_opdl.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_opdl.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_skeleton.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_skeleton.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_skeleton.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_skeleton.so
rm /usr/local/lib/x86_64-linux-gnu/librte_event_sw.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_sw.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_sw.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_event_sw.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_acc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_acc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_acc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_acc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_fpga_5gnr_fec.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_5gnr_fec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_5gnr_fec.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_5gnr_fec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_fpga_lte_fec.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_lte_fec.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_lte_fec.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_fpga_lte_fec.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_la12xx.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_la12xx.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_la12xx.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_la12xx.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_null.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_null.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_null.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_null.so
rm /usr/local/lib/x86_64-linux-gnu/librte_baseband_turbo_sw.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_turbo_sw.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_turbo_sw.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_baseband_turbo_sw.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_acpi.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_acpi.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_acpi.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_acpi.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_amd_pstate.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_amd_pstate.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_amd_pstate.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_amd_pstate.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_cppc.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_cppc.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_cppc.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_cppc.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_intel_pstate.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_pstate.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_pstate.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_pstate.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_intel_uncore.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_uncore.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_uncore.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_intel_uncore.so
rm /usr/local/lib/x86_64-linux-gnu/librte_power_kvm_vm.a
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_kvm_vm.so.26.0
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_kvm_vm.so.26
rm /usr/local/lib/x86_64-linux-gnu/dpdk/pmds-26.0/librte_power_kvm_vm.so
rm /usr/local/bin/dpdk-dumpcap
rm /usr/local/bin/dpdk-graph
rm /usr/local/bin/dpdk-pdump
rm /usr/local/bin/dpdk-proc-info
rm /usr/local/bin/dpdk-test-acl
rm /usr/local/bin/dpdk-test-bbdev
rm /usr/local/bin/dpdk-test-cmdline
rm /usr/local/bin/dpdk-test-compress-perf
rm /usr/local/bin/dpdk-test-crypto-perf
rm /usr/local/bin/dpdk-test-dma-perf
rm /usr/local/bin/dpdk-test-eventdev
rm /usr/local/bin/dpdk-test-fib
rm /usr/local/bin/dpdk-test-flow-perf
rm /usr/local/bin/dpdk-test-gpudev
rm /usr/local/bin/dpdk-test-mldev
rm /usr/local/bin/dpdk-test-pipeline
rm /usr/local/bin/dpdk-testpmd
rm /usr/local/bin/dpdk-test-regex
rm /usr/local/bin/dpdk-test-sad
rm /usr/local/bin/dpdk-test-security-perf
rm /usr/local/bin/dpdk-test
rm /usr/local/include/rte_config.h
rm /usr/local/include/rte_atomic.h
rm /usr/local/include/rte_byteorder.h
rm /usr/local/include/rte_cpuflags.h
rm /usr/local/include/rte_cycles.h
rm /usr/local/include/rte_io.h
rm /usr/local/include/rte_memcpy.h
rm /usr/local/include/rte_pause.h
rm /usr/local/include/rte_power_intrinsics.h
rm /usr/local/include/rte_prefetch.h
rm /usr/local/include/rte_rtm.h
rm /usr/local/include/rte_rwlock.h
rm /usr/local/include/rte_spinlock.h
rm /usr/local/include/rte_vect.h
rm /usr/local/include/rte_atomic_32.h
rm /usr/local/include/rte_atomic_64.h
rm /usr/local/include/rte_byteorder_32.h
rm /usr/local/include/rte_byteorder_64.h
rm /usr/local/include/rte_log.h
rm /usr/local/include/rte_kvargs.h
rm /usr/local/include/rte_argparse.h
rm /usr/local/include/rte_telemetry.h
rm /usr/local/include/rte_pmu.h
rm /usr/local/include/rte_alarm.h
rm /usr/local/include/rte_bitmap.h
rm /usr/local/include/rte_bitops.h
rm /usr/local/include/rte_bitset.h
rm /usr/local/include/rte_branch_prediction.h
rm /usr/local/include/rte_bus.h
rm /usr/local/include/rte_class.h
rm /usr/local/include/rte_common.h
rm /usr/local/include/rte_compat.h
rm /usr/local/include/rte_debug.h
rm /usr/local/include/rte_dev.h
rm /usr/local/include/rte_devargs.h
rm /usr/local/include/rte_eal.h
rm /usr/local/include/rte_eal_memconfig.h
rm /usr/local/include/rte_eal_trace.h
rm /usr/local/include/rte_errno.h
rm /usr/local/include/rte_epoll.h
rm /usr/local/include/rte_fbarray.h
rm /usr/local/include/rte_hexdump.h
rm /usr/local/include/rte_hypervisor.h
rm /usr/local/include/rte_interrupts.h
rm /usr/local/include/rte_keepalive.h
rm /usr/local/include/rte_launch.h
rm /usr/local/include/rte_lcore.h
rm /usr/local/include/rte_lcore_var.h
rm /usr/local/include/rte_lock_annotations.h
rm /usr/local/include/rte_malloc.h
rm /usr/local/include/rte_mcslock.h
rm /usr/local/include/rte_memory.h
rm /usr/local/include/rte_memzone.h
rm /usr/local/include/rte_pci_dev_feature_defs.h
rm /usr/local/include/rte_pci_dev_features.h
rm /usr/local/include/rte_per_lcore.h
rm /usr/local/include/rte_pflock.h
rm /usr/local/include/rte_random.h
rm /usr/local/include/rte_reciprocal.h
rm /usr/local/include/rte_seqcount.h
rm /usr/local/include/rte_seqlock.h
rm /usr/local/include/rte_service.h
rm /usr/local/include/rte_service_component.h
rm /usr/local/include/rte_stdatomic.h
rm /usr/local/include/rte_string_fns.h
rm /usr/local/include/rte_tailq.h
rm /usr/local/include/rte_thread.h
rm /usr/local/include/rte_ticketlock.h
rm /usr/local/include/rte_time.h
rm /usr/local/include/rte_trace.h
rm /usr/local/include/rte_trace_point.h
rm /usr/local/include/rte_trace_point_register.h
rm /usr/local/include/rte_uuid.h
rm /usr/local/include/rte_version.h
rm /usr/local/include/rte_vfio.h
rm /usr/local/include/rte_os.h
rm /usr/local/include/rte_ptr_compress.h
rm /usr/local/include/rte_ring.h
rm /usr/local/include/rte_soring.h
rm /usr/local/include/rte_rcu_qsbr.h
rm /usr/local/include/rte_mempool.h
rm /usr/local/include/rte_mempool_trace_fp.h
rm /usr/local/include/rte_mbuf.h
rm /usr/local/include/rte_mbuf_core.h
rm /usr/local/include/rte_mbuf_ptype.h
rm /usr/local/include/rte_mbuf_pool_ops.h
rm /usr/local/include/rte_mbuf_dyn.h
rm /usr/local/include/rte_mbuf_history.h
rm /usr/local/include/rte_cksum.h
rm /usr/local/include/rte_ip.h
rm /usr/local/include/rte_ip4.h
rm /usr/local/include/rte_ip6.h
rm /usr/local/include/rte_tcp.h
rm /usr/local/include/rte_udp.h
rm /usr/local/include/rte_tls.h
rm /usr/local/include/rte_dtls.h
rm /usr/local/include/rte_esp.h
rm /usr/local/include/rte_sctp.h
rm /usr/local/include/rte_icmp.h
rm /usr/local/include/rte_arp.h
rm /usr/local/include/rte_ether.h
rm /usr/local/include/rte_macsec.h
rm /usr/local/include/rte_vxlan.h
rm /usr/local/include/rte_gre.h
rm /usr/local/include/rte_gtp.h
rm /usr/local/include/rte_net.h
rm /usr/local/include/rte_net_crc.h
rm /usr/local/include/rte_mpls.h
rm /usr/local/include/rte_higig.h
rm /usr/local/include/rte_ecpri.h
rm /usr/local/include/rte_pdcp_hdr.h
rm /usr/local/include/rte_geneve.h
rm /usr/local/include/rte_l2tpv2.h
rm /usr/local/include/rte_ppp.h
rm /usr/local/include/rte_ib.h
rm /usr/local/include/rte_meter.h
rm /usr/local/include/rte_cman.h
rm /usr/local/include/rte_ethdev.h
rm /usr/local/include/rte_ethdev_trace_fp.h
rm /usr/local/include/rte_dev_info.h
rm /usr/local/include/rte_flow.h
rm /usr/local/include/rte_mtr.h
rm /usr/local/include/rte_tm.h
rm /usr/local/include/rte_pci.h
rm /usr/local/include/cmdline.h
rm /usr/local/include/cmdline_parse.h
rm /usr/local/include/cmdline_parse_num.h
rm /usr/local/include/cmdline_parse_bool.h
rm /usr/local/include/cmdline_parse_ipaddr.h
rm /usr/local/include/cmdline_parse_etheraddr.h
rm /usr/local/include/cmdline_parse_string.h
rm /usr/local/include/cmdline_rdline.h
rm /usr/local/include/cmdline_vt100.h
rm /usr/local/include/cmdline_socket.h
rm /usr/local/include/cmdline_cirbuf.h
rm /usr/local/include/cmdline_parse_portlist.h
rm /usr/local/include/rte_metrics.h
rm /usr/local/include/rte_metrics_telemetry.h
rm /usr/local/include/rte_fbk_hash.h
rm /usr/local/include/rte_hash_crc.h
rm /usr/local/include/rte_hash.h
rm /usr/local/include/rte_jhash.h
rm /usr/local/include/rte_thash.h
rm /usr/local/include/rte_thash_gfni.h
rm /usr/local/include/rte_timer.h
rm /usr/local/include/rte_acl.h
rm /usr/local/include/rte_acl_osdep.h
rm /usr/local/include/rte_bbdev.h
rm /usr/local/include/rte_bbdev_op.h
rm /usr/local/include/rte_bbdev_trace_fp.h
rm /usr/local/include/rte_bitrate.h
rm /usr/local/include/bpf_def.h
rm /usr/local/include/rte_bpf.h
rm /usr/local/include/rte_bpf_ethdev.h
rm /usr/local/include/rte_cfgfile.h
rm /usr/local/include/rte_compressdev.h
rm /usr/local/include/rte_comp.h
rm /usr/local/include/rte_cryptodev.h
rm /usr/local/include/rte_cryptodev_trace_fp.h
rm /usr/local/include/rte_crypto.h
rm /usr/local/include/rte_crypto_sym.h
rm /usr/local/include/rte_crypto_asym.h
rm /usr/local/include/rte_distributor.h
rm /usr/local/include/rte_dmadev.h
rm /usr/local/include/rte_efd.h
rm /usr/local/include/rte_event_crypto_adapter.h
rm /usr/local/include/rte_event_dma_adapter.h
rm /usr/local/include/rte_event_eth_rx_adapter.h
rm /usr/local/include/rte_event_eth_tx_adapter.h
rm /usr/local/include/rte_event_ring.h
rm /usr/local/include/rte_event_timer_adapter.h
rm /usr/local/include/rte_event_vector_adapter.h
rm /usr/local/include/rte_eventdev.h
rm /usr/local/include/rte_eventdev_trace_fp.h
rm /usr/local/include/rte_dispatcher.h
rm /usr/local/include/rte_gpudev.h
rm /usr/local/include/rte_gro.h
rm /usr/local/include/rte_gso.h
rm /usr/local/include/rte_ip_frag.h
rm /usr/local/include/rte_jobstats.h
rm /usr/local/include/rte_latencystats.h
rm /usr/local/include/rte_lpm.h
rm /usr/local/include/rte_lpm6.h
rm /usr/local/include/rte_member.h
rm /usr/local/include/rte_pcapng.h
rm /usr/local/include/rte_power_cpufreq.h
rm /usr/local/include/rte_power_pmd_mgmt.h
rm /usr/local/include/rte_power_qos.h
rm /usr/local/include/rte_power_uncore.h
rm /usr/local/include/rte_rawdev.h
rm /usr/local/include/rte_regexdev.h
rm /usr/local/include/rte_mldev.h
rm /usr/local/include/rte_rib.h
rm /usr/local/include/rte_rib6.h
rm /usr/local/include/rte_reorder.h
rm /usr/local/include/rte_approx.h
rm /usr/local/include/rte_red.h
rm /usr/local/include/rte_sched.h
rm /usr/local/include/rte_sched_common.h
rm /usr/local/include/rte_pie.h
rm /usr/local/include/rte_security.h
rm /usr/local/include/rte_stack.h
rm /usr/local/include/rte_vdpa.h
rm /usr/local/include/rte_vhost.h
rm /usr/local/include/rte_vhost_async.h
rm /usr/local/include/rte_vhost_crypto.h
rm /usr/local/include/rte_ipsec.h
rm /usr/local/include/rte_ipsec_sa.h
rm /usr/local/include/rte_ipsec_sad.h
rm /usr/local/include/rte_pdcp.h
rm /usr/local/include/rte_fib.h
rm /usr/local/include/rte_fib6.h
rm /usr/local/include/rte_port_ethdev.h
rm /usr/local/include/rte_port_fd.h
rm /usr/local/include/rte_port_frag.h
rm /usr/local/include/rte_port_ras.h
rm /usr/local/include/rte_port.h
rm /usr/local/include/rte_port_ring.h
rm /usr/local/include/rte_port_sched.h
rm /usr/local/include/rte_port_source_sink.h
rm /usr/local/include/rte_port_sym_crypto.h
rm /usr/local/include/rte_port_eventdev.h
rm /usr/local/include/rte_swx_port.h
rm /usr/local/include/rte_swx_port_ethdev.h
rm /usr/local/include/rte_swx_port_fd.h
rm /usr/local/include/rte_swx_port_ring.h
rm /usr/local/include/rte_swx_port_source_sink.h
rm /usr/local/include/rte_pdump.h
rm /usr/local/include/rte_lru.h
rm /usr/local/include/rte_swx_hash_func.h
rm /usr/local/include/rte_swx_table.h
rm /usr/local/include/rte_swx_table_em.h
rm /usr/local/include/rte_swx_table_learner.h
rm /usr/local/include/rte_swx_table_selector.h
rm /usr/local/include/rte_swx_table_wm.h
rm /usr/local/include/rte_table.h
rm /usr/local/include/rte_table_acl.h
rm /usr/local/include/rte_table_array.h
rm /usr/local/include/rte_table_hash.h
rm /usr/local/include/rte_table_hash_cuckoo.h
rm /usr/local/include/rte_table_hash_func.h
rm /usr/local/include/rte_table_lpm.h
rm /usr/local/include/rte_table_lpm_ipv6.h
rm /usr/local/include/rte_table_stub.h
rm /usr/local/include/rte_pipeline.h
rm /usr/local/include/rte_port_in_action.h
rm /usr/local/include/rte_table_action.h
rm /usr/local/include/rte_swx_ipsec.h
rm /usr/local/include/rte_swx_pipeline.h
rm /usr/local/include/rte_swx_extern.h
rm /usr/local/include/rte_swx_ctl.h
rm /usr/local/include/rte_graph.h
rm /usr/local/include/rte_graph_worker.h
rm /usr/local/include/rte_graph_feature_arc.h
rm /usr/local/include/rte_graph_feature_arc_worker.h
rm /usr/local/include/rte_node_eth_api.h
rm /usr/local/include/rte_node_ip4_api.h
rm /usr/local/include/rte_node_ip6_api.h
rm /usr/local/include/rte_node_mbuf_dynfield.h
rm /usr/local/include/rte_node_pkt_cls_api.h
rm /usr/local/include/rte_node_udp4_input_api.h
rm /usr/local/include/rte_pmd_dpaax_qdma.h
rm /usr/local/include/rte_bus_pci.h
rm /usr/local/include/rte_bus_vdev.h
rm /usr/local/include/rte_bus_vmbus.h
rm /usr/local/include/rte_vmbus_reg.h
rm /usr/local/include/rte_pmd_cnxk_mempool.h
rm /usr/local/include/rte_dpaa2_mempool.h
rm /usr/local/include/rte_avp_common.h
rm /usr/local/include/rte_avp_fifo.h
rm /usr/local/include/rte_pmd_bnxt.h
rm /usr/local/include/rte_eth_bond.h
rm /usr/local/include/rte_eth_bond_8023ad.h
rm /usr/local/include/rte_pmd_cnxk.h
rm /usr/local/include/rte_pmd_dpaa.h
rm /usr/local/include/rte_pmd_dpaa2.h
rm /usr/local/include/rte_pmd_i40e.h
rm /usr/local/include/rte_pmd_iavf.h
rm /usr/local/include/rte_pmd_ixgbe.h
rm /usr/local/include/rte_pmd_mlx5.h
rm /usr/local/include/rte_pmd_ntnic.h
rm /usr/local/include/rte_eth_ring.h
rm /usr/local/include/rte_eth_softnic.h
rm /usr/local/include/rte_pmd_txgbe.h
rm /usr/local/include/rte_eth_vhost.h
rm /usr/local/include/rte_pmd_bphy.h
rm /usr/local/include/rte_pmd_cnxk_gpio.h
rm /usr/local/include/rte_pmd_dpaa2_cmdif.h
rm /usr/local/include/rte_pmd_ifpga.h
rm /usr/local/include/rte_pmd_ntb.h
rm /usr/local/include/rte_pmd_cnxk_crypto.h
rm /usr/local/include/rte_cryptodev_scheduler.h
rm /usr/local/include/rte_cryptodev_scheduler_operations.h
rm /usr/local/include/rte_pmd_cnxk_eventdev.h
rm /usr/local/include/rte_pmd_dlb2.h
rm /usr/local/include/rte_acc_cfg.h
rm /usr/local/include/rte_acc_common_cfg.h
rm /usr/local/include/rte_pmd_fpga_5gnr_fec.h
rm /usr/local/include/rte_power_guest_channel.h
rm /usr/local/include/rte_pmu_pmc_x86_64.h
rm /usr/local/include/rte_ring_core.h
rm /usr/local/include/rte_ring_elem.h
rm /usr/local/include/rte_ring_elem_pvt.h
rm /usr/local/include/rte_ring_c11_pvt.h
rm /usr/local/include/rte_ring_generic_pvt.h
rm /usr/local/include/rte_ring_hts.h
rm /usr/local/include/rte_ring_hts_elem_pvt.h
rm /usr/local/include/rte_ring_peek.h
rm /usr/local/include/rte_ring_peek_elem_pvt.h
rm /usr/local/include/rte_ring_peek_zc.h
rm /usr/local/include/rte_ring_rts.h
rm /usr/local/include/rte_ring_rts_elem_pvt.h
rm /usr/local/include/rte_ethdev_core.h
rm /usr/local/include/rte_eth_ctrl.h
rm /usr/local/include/rte_crc_arm64.h
rm /usr/local/include/rte_crc_generic.h
rm /usr/local/include/rte_crc_sw.h
rm /usr/local/include/rte_crc_x86.h
rm /usr/local/include/rte_thash_x86_gfni.h
rm /usr/local/include/rte_cryptodev_core.h
rm /usr/local/include/rte_dmadev_core.h
rm /usr/local/include/rte_dmadev_trace_fp.h
rm /usr/local/include/rte_eventdev_core.h
rm /usr/local/include/rte_lpm_altivec.h
rm /usr/local/include/rte_lpm_neon.h
rm /usr/local/include/rte_lpm_scalar.h
rm /usr/local/include/rte_lpm_sse.h
rm /usr/local/include/rte_lpm_sve.h
rm /usr/local/include/rte_lpm_rvv.h
rm /usr/local/include/rte_regexdev_core.h
rm /usr/local/include/rte_stack_std.h
rm /usr/local/include/rte_stack_lf.h
rm /usr/local/include/rte_stack_lf_generic.h
rm /usr/local/include/rte_stack_lf_c11.h
rm /usr/local/include/rte_stack_lf_stubs.h
rm /usr/local/include/rte_ipsec_group.h
rm /usr/local/include/rte_pdcp_group.h
rm /usr/local/include/rte_lru_arm64.h
rm /usr/local/include/rte_lru_x86.h
rm /usr/local/include/rte_table_hash_func_arm64.h
rm /usr/local/include/rte_graph_model_mcore_dispatch.h
rm /usr/local/include/rte_graph_model_rtc.h
rm /usr/local/include/rte_graph_worker_common.h
rm /usr/local/include/generic/rte_atomic.h
rm /usr/local/include/generic/rte_byteorder.h
rm /usr/local/include/generic/rte_cpuflags.h
rm /usr/local/include/generic/rte_cycles.h
rm /usr/local/include/generic/rte_io.h
rm /usr/local/include/generic/rte_memcpy.h
rm /usr/local/include/generic/rte_pause.h
rm /usr/local/include/generic/rte_power_intrinsics.h
rm /usr/local/include/generic/rte_prefetch.h
rm /usr/local/include/generic/rte_rwlock.h
rm /usr/local/include/generic/rte_spinlock.h
rm /usr/local/include/generic/rte_vect.h
rm /usr/local/bin/dpdk-cmdline-gen.py
rm /usr/local/bin/dpdk-devbind.py
rm /usr/local/bin/dpdk-pmdinfo.py
rm /usr/local/bin/dpdk-telemetry.py
rm /usr/local/bin/dpdk-hugepages.py
rm /usr/local/bin/dpdk-rss-flows.py
rm /usr/local/bin/dpdk-telemetry-exporter.py
rm /usr/local/include/rte_build_config.h
rm /usr/local/lib/x86_64-linux-gnu/pkgconfig/libdpdk-libs.pc
rm /usr/local/lib/x86_64-linux-gnu/pkgconfig/libdpdk.pc