/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2022 Intel Corporation
 */

#ifndef _ST_LIB_ERR_HEAD_H_
#define _ST_LIB_ERR_HEAD_H_

/* internal ret code for debug usage */
enum sti_ret_code {
  STI_SUSS = 0,
  STI_ERROR_1,
  /* rl trs stat */
  STI_RLTRS_BURST_INFLIGHT_FAIL = 100,
  STI_RLTRS_BURST_INFLIGHT2_FAIL,
  STI_RLTRS_BURST_PAD_INFLIGHT_FAIL,
  STI_RLTRS_TARGET_TSC_NOT_REACH,
  STI_RLTRS_DEQUEUE_FAIL,
  STI_RLTRS_BURST_HAS_DUMMY,
  STI_RLTRS_1ST_PKT_TSC,
  STI_RLTRS_BURST_FAIL,
  /* tsc trs stat */
  STI_TSCTRS_BURST_INFLIGHT_FAIL = 140,
  STI_TSCTRS_TARGET_TSC_NOT_REACH,
  STI_TSCTRS_DEQUEUE_FAIL,
  STI_TSCTRS_BURST_HAS_DUMMY,
  STI_TSCTRS_PKT_DEQUEUE_FAIL,
  STI_TSCTRS_PKT_ENQUEUE_FAIL,
  STI_TSCTRS_INFLIGHT_TSC_NOT_REACH,
  STI_TSCTRS_INFLIGHT_ENQUEUE_FAIL,
  STI_TSCTRS_BURST_FAIL,
  /* st frame build stat */
  STI_FRAME_RING_FULL = 200,
  STI_FRAME_INFLIGHT_ENQUEUE_FAIL,
  STI_FRAME_INFLIGHT_R_ENQUEUE_FAIL,
  STI_FRAME_APP_GET_FRAME_BUSY,
  STI_FRAME_APP_ERR_TX_FRAME,
  STI_FRAME_APP_ERR_USER_META,
  STI_FRAME_APP_SLICE_NOT_READY,
  STI_FRAME_PKT_ALLOC_FAIL,
  STI_FRAME_PKT_ENQUEUE_FAIL,
  STI_FRAME_PKT_R_ENQUEUE_FAIL,
  STI_FRAME_PKT_ALLOC_CHAIN_FAIL,
  STI_FRAME_PKT_ALLOC_R_FAIL,
  STI_FRAME_PKT_ALLOC_COPY_FAIL,
  STI_FRAME_ANC_TOO_LARGE,
  /* st rtp build stat */
  STI_RTP_RING_FULL = 240,
  STI_RTP_INFLIGHT_ENQUEUE_FAIL,
  STI_RTP_INFLIGHT_R_ENQUEUE_FAIL,
  STI_RTP_APP_DEQUEUE_FAIL,
  STI_RTP_PKT_ALLOC_FAIL,
  STI_RTP_PKT_ENQUEUE_FAIL,
  STI_RTP_PKT_R_ENQUEUE_FAIL,
  /* st22 frame build stat */
  STI_ST22_RING_FULL = 280,
  STI_ST22_INFLIGHT_ENQUEUE_FAIL,
  STI_ST22_INFLIGHT_R_ENQUEUE_FAIL,
  STI_ST22_APP_GET_FRAME_BUSY,
  STI_ST22_APP_ERR_TX_FRAME,
  STI_ST22_APP_GET_FRAME_ERR_SIZE,
  STI_ST22_APP_SLICE_NOT_READY,
  STI_ST22_PKT_ALLOC_FAIL,
  STI_ST22_PKT_ENQUEUE_FAIL,
  STI_ST22_PKT_R_ENQUEUE_FAIL,
};

#endif
