name: ubuntu-build

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - name: run script  
      shell: bash
      working-directory: "${{ github.workspace }}/.github/scripts"
      run: sudo -E ./setup_environment.sh