name: Setup capture PTP and phc2sys
description: Detect capture interface/PTP clock (prefers 2nd PF) and start phc2sys; also exports MTL_GITHUB_WORKFLOW for PCAP naming
inputs:
  pci_device:
    description: PCI device ID(s) (vendor:device) used by the runner (e.g., 8086:1592 or 8086:1592,8086:1592)
    required: true
  mtl_github_workflow:
    description: Value for MTL_GITHUB_WORKFLOW (e.g., "nightly-pytest:e810")
    required: true
runs:
  using: composite
  steps:
    - name: Export workflow tag and start phc2sys
      shell: bash
      env:
        PCI_DEVICE: ${{ inputs.pci_device }}
        MTL_GITHUB_WORKFLOW: ${{ inputs.mtl_github_workflow }}
      run: |
        set -euo pipefail

        echo "MTL_GITHUB_WORKFLOW=${MTL_GITHUB_WORKFLOW}" >> "$GITHUB_ENV"

        echo "PCI_DEVICE=${PCI_DEVICE}"

        pci_ids_csv="${PCI_DEVICE// /}"
        IFS=',' read -r -a pci_ids <<< "${pci_ids_csv}"

        mapfile -t bdfs < <(
          lspci -Dn | awk -v ids="${pci_ids[*]}" '
            BEGIN { split(ids, a, " "); for (i in a) wanted[a[i]] = 1 }
            wanted[$3] { print $1 }
          ' | sort -u
        )
        if [ "${#bdfs[@]}" -lt 1 ]; then
          echo "ERROR: no PCI functions found matching ${PCI_DEVICE}" >&2
          exit 1
        fi

        # Prefer the 2nd PF when present.
        capture_bdf="${bdfs[1]:-${bdfs[0]}}"
        if [ ! -d "/sys/bus/pci/devices/${capture_bdf}/net" ]; then
          echo "ERROR: no netdevs under /sys/bus/pci/devices/${capture_bdf}/net" >&2
          ls -la "/sys/bus/pci/devices/${capture_bdf}" || true
          exit 1
        fi

        capture_iface="$(ls "/sys/bus/pci/devices/${capture_bdf}/net" | head -n 1)"
        if [ -z "${capture_iface}" ]; then
          echo "ERROR: failed to detect interface name for ${capture_bdf}" >&2
          exit 1
        fi

        ptp_idx="$(sudo ethtool -T "${capture_iface}" 2>/dev/null | awk -F': ' '/PTP Hardware Clock:/ {print $2; exit}')"
        if ! [[ "${ptp_idx}" =~ ^[0-9]+$ ]]; then
          echo "ERROR: failed to parse PTP Hardware Clock index for ${capture_iface}" >&2
          sudo ethtool -T "${capture_iface}" || true
          exit 1
        fi

        capture_ptp="/dev/ptp${ptp_idx}"

        echo "CAPTURE_BDF=${capture_bdf}" >> "$GITHUB_ENV"
        echo "CAPTURE_IFACE=${capture_iface}" >> "$GITHUB_ENV"
        echo "CAPTURE_PTP=${capture_ptp}" >> "$GITHUB_ENV"

        echo "Capture interface: ${capture_iface} (${capture_bdf}), PTP: ${capture_ptp}"
        echo "Starting phc2sys: ${capture_ptp} -> CLOCK_REALTIME (iface=${capture_iface})"
        sudo phc2sys -s "${capture_ptp}" -c CLOCK_REALTIME -O 0 -m &
