# Copyright (c) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

services:
  imtl:
    build:
      context: ..
      dockerfile: docker/${MTL_VARIANT:-ubuntu22}.dockerfile
      target: final
      args:
        HTTP_PROXY: ${HTTP_PROXY:-${http_proxy:-}}
        HTTPS_PROXY: ${HTTPS_PROXY:-${https_proxy:-}}
    image: mtl:${MTL_VARIANT:-ubuntu22}
    init: true
    stdin_open: true
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    devices:
      - "/dev/vfio:/dev/vfio"
    volumes:
      - "/var/run/imtl:/var/run/imtl"
    cap_add:
      - SYS_NICE
      - IPC_LOCK