[package]
name = "imtl-rs"
version = "0.1.1"
edition = "2021"

[lib]
name = "imtl"
path = "src/imtl/lib.rs"

[dependencies]
derive_builder = "0.12.0"

[dependencies.imtl-sys]
path = "imtl-sys"
version = "^0.1.0"

[dependencies.bitflags]
version = "2.4.1"

[features]
convert = ["imtl-sys/convert"]
pipeline = ["imtl-sys/pipeline"]
