name: Cleanup Processes
description: Kill any running DPDK or MTL related processes
runs:
  using: composite
  steps:
    - name: Cleanup processes
      shell: bash
      run: |
        sudo killall -SIGKILL gtest.sh KahawaiTest ffmpeg gst-launch-1.0 RxTxApp || true
        sudo killall -SIGINT pytest MtlManager phc2sys ptp4l netsniff-ng || true
        sleep 2
        sudo "$GITHUB_ACTION_PATH/../../../tests/tools/isolate/isolate.sh" --sweep
