name: Base Build

on:
  # allow manually trigger
  workflow_dispatch:
  push:
    branches:
      - main
      - 'maint-**'
  pull_request:
    branches:
      - main
      - 'maint-**'
env:
  MTL_BUILD_AND_INSTALL: 1
  SETUP_ENVIRONMENT: 1
  CICD_BUILD: 1
  SETUP_BUILD_AND_INSTALL_ICE_DRIVER: 0
  CICD_BUILD_BUILD_ICE_DRIVER: 0
  SETUP_BUILD_AND_INSTALL_DPDK: 1
  SETUP_BUILD_AND_INSTALL_EBPF_XDP: 0
  SETUP_BUILD_AND_INSTALL_GPU_DIRECT: 1
  HOOK_RUST: 1
  HOOK_PYTHON: 1
  ECOSYSTEM_BUILD_AND_INSTALL_FFMPEG_PLUGIN: 1
  ECOSYSTEM_BUILD_AND_INSTALL_GSTREAMER_PLUGIN: 1
  ECOSYSTEM_BUILD_AND_INSTALL_RIST_PLUGIN: 1
  ECOSYSTEM_BUILD_AND_INSTALL_OBS_PLUGIN: 1
  TOOLS_BUILD_AND_INSTALL_MTL_MONITORS: 0
  TOOLS_BUILD_AND_INSTALL_MTL_READCAP: 1
  TOOLS_BUILD_AND_INSTALL_MTL_CPU_EMULATOR: 1

permissions:
  contents: read
jobs:
  changes:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      # https://stackoverflow.com/questions/70326569/github-workflow-how-to-conditionally-setup-env-for-all-subsequent-jobs
      ubuntu_build: ${{ steps.filter.outputs.ubuntu_build == 'true' }}
      manager_build: ${{ steps.filter.outputs.manager_build == 'true' }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: .github/path_filters.yml

  ubuntu-build:
    needs: changes
    if: ${{ github.repository == 'OpenVisualCloud/Media-Transport-Library' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Release
        if: ${{ needs.changes.outputs.ubuntu_build == 'true' }}
        run: sudo -E .github/scripts/setup_environment.sh

      - name: 'upload release build artifacts'
        if: ${{ needs.changes.outputs.ubuntu_build == 'true' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mtl-release-bin
          path: '${{ github.workspace }}/build/'

  ubuntu-ebpf-xdp-build:
    needs: changes
    if: ${{ github.repository == 'OpenVisualCloud/Media-Transport-Library' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ebpf-xdp build
        if: ${{ needs.changes.outputs.ubuntu_build == 'true' }}
        run: sudo -E .github/scripts/setup_environment.sh
        env:
          SETUP_BUILD_AND_INSTALL_EBPF_XDP: 1
          TOOLS_BUILD_AND_INSTALL_MTL_MONITORS: 1
