name: gtest-bare-metal

on:
  # allow manually trigger
  workflow_dispatch:
    inputs:
      branch-to-checkout:
        type: string
        default: 'main'
        required: false
        description: 'Branch name to use'
  push:
    branches:
      - main
      - 'maint-**'
  pull_request:
    branches:
      - main
      - 'maint-**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gtest-check-for-changes:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.linux_tests == 'true' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: .github/path_filters.yml

  run-gtest-tests:
    needs: gtest-check-for-changes
    if: ${{ github.repository == 'OpenVisualCloud/Media-Transport-Library' }}
    strategy:
      matrix:
        nic:
          - e810
          - e810-dell
          - e830
      fail-fast: false
    runs-on: ${{ matrix.nic }}
    steps:
      - name: Harden Runner
        if: ${{ needs.gtest-check-for-changes.outputs.changed == 'true' && github.event_name != 'workflow_dispatch' }}
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout MTL
        if: ${{ needs.gtest-check-for-changes.outputs.changed == 'true' && github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: '${{ inputs.branch-to-checkout || github.sha || github.ref }}'

      - name: Build
        if: ${{ needs.gtest-check-for-changes.outputs.changed == 'true' && github.event_name != 'workflow_dispatch' }}
        uses: ./.github/actions/build

      - name: run gtest bare metal
        if: ${{ needs.gtest-check-for-changes.outputs.changed == 'true' && github.event_name != 'workflow_dispatch' }}
        env:
          NIGHTLY: 0
          EXIT_ON_FAILURE: 1
        run: sudo -E "${{ github.workspace }}/.github/scripts/gtest.sh"
