name: Windows MSYS2 build

on:
  # allow manually trigger
  workflow_dispatch:

env:
  # FIXME: For some reason enabling jit debugging "fixes" random python crashes
  # see https://github.com/msys2/MINGW-packages/issues/11864 and
  # https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3280#note_1678973
  MSYS: winjitdebug

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.msys2_build == 'true' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: .github/path_filters.yml

  build:
    needs: changes
    if: ${{ github.repository == 'OpenVisualCloud/Media-Transport-Library' && needs.changes.outputs.changed == 'true' }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
          - ucrt64
        dpdk: [25.03, 23.11]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Install dependencies
        uses: msys2/setup-msys2@7efe20baefed56359985e327d329042cde2434ff # v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            pkgconf:p
            openssl:p
            gcc:p
            meson:p
            json-c:p
            libpcap:p
            gtest:p
            SDL2:p
            SDL2_ttf:p
            dlfcn:p

      - name: Checkout IMTL code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0

      - name: Install npcap-sdk
        run: task ci:msys2 -- npcap

      - name: Checkout mman-win32 code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: 'alitrack/mman-win32'
          ref: master
          path: mman-win32

      - name: Build and install mman-win32
        run: task ci:msys2 -- mman

      - name: Convert patches for DPDK
        env:
          DPDK_VERSION: ${{ matrix.dpdk }}
        run: task ci:msys2 -- convert-patches

      - name: Hash DPDK patches
        id: hash-patches
        env:
          DPDK_VERSION: ${{ matrix.dpdk }}
        run: task ci:msys2 -- hash-patches

      - name: Cache DPDK
        id: cache-dpdk
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: dpdk
          key: dpdk-${{ matrix.dpdk }}-${{ matrix.sys }}-${{ steps.hash-patches.outputs.hash }}

      - name: Checkout DPDK code
        if: ${{ steps.cache-dpdk.outputs.cache-hit != 'true' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: 'DPDK/dpdk'
          ref: v${{matrix.dpdk}}
          path: dpdk
          clean: true

      - name: Apply patches for DPDK
        if: ${{ steps.cache-dpdk.outputs.cache-hit != 'true' }}
        shell: bash
        env:
          DPDK_VERSION: ${{ matrix.dpdk }}
        run: task ci:msys2 -- apply-patches

      - name: Build and install DPDK
        if: ${{ steps.cache-dpdk.outputs.cache-hit != 'true' }}
        run: task ci:msys2 -- build-dpdk

      - name: Install cached DPDK
        if: ${{ steps.cache-dpdk.outputs.cache-hit == 'true' }}
        run: task ci:msys2 -- install-dpdk

      - name: Build
        run: task ci:msys2 -- build

      - name: Build with debug
        run: task ci:msys2 -- build-debug

      - name: Build with TAP
        run: task ci:msys2 -- build-tap
