name: validation-bare-metal

on:
  # allow manually trigger
  workflow_dispatch:
    inputs:
      branch-to-checkout:
        type: string
        default: 'main'
        required: false
        description: 'Branch name to use'
      validation-iface-binding:
        type: choice
        required: true
        description: 'Type of iface binding to use'
        options:
          - "create_vf"
          - "create_kvf"
          - "create_tvf"
          - "bind_pmd"
          - "bind_kernel"
      validation-test-port-p:
        type: choice
        required: true
        description: 'Which to use as Test-Port-P'
        options:
          - TEST_VF_PORT_P_0
          - TEST_VF_PORT_P_1
          - TEST_VF_PORT_P_2
          - TEST_PF_PORT_P
          - TEST_VF_PORT_R_0
          - TEST_VF_PORT_R_1
          - TEST_VF_PORT_R_2
          - TEST_PF_PORT_R
          - TEST_DMA_PORT_P
          - TEST_DMA_PORT_R
      validation-test-port-r:
        type: choice
        required: true
        description: 'Which to use as Test-Port-R'
        options:
          - TEST_VF_PORT_P_1
          - TEST_VF_PORT_P_0
          - TEST_VF_PORT_P_2
          - TEST_PF_PORT_P
          - TEST_VF_PORT_R_0
          - TEST_VF_PORT_R_1
          - TEST_VF_PORT_R_2
          - TEST_PF_PORT_R
          - TEST_DMA_PORT_P
          - TEST_DMA_PORT_R
      validation-no-fail-tests:
        type: choice
        required: false
        description: 'Run all tests, non will fail'
        options:
          - "true"
          - "false"
      validation-tests-1:
        type: string
        default: 'single/video/pacing'
        required: true
        description: '1st validation tests to run'
      validation-tests-2:
        type: string
        default: 'single/ancillary'
        required: false
        description: '2nd validation tests to run'
      validation-pre-release-1:
        description: 'Select from pre-release group tests nr-1'
        required: false
        type: choice
        options:
          - NONE
          - ancillary
          - kernel-socket
          - rss-mode
          - st20p
          - st30p
          - st41
          - udp
          - video
          - xdp
      validation-pre-release-2:
        description: 'Select from pre-release group tests nr-2'
        required: false
        type: choice
        options:
          - NONE
          - ffmpeg-plugin
          - fuzzy-tests
          - performance
          - ptp
          - rx-timing
          - vero
          - virtio-enable
          - wrong-parameter
      validation-pre-release-3:
        description: 'Select from pre-release group tests nr-3'
        required: false
        type: choice
        options:
          - NONE
          - gpu-direct
          - gpu-enabling

env:
  BUILD_TYPE: 'Release'
  DPDK_VERSION: '25.11'
  DPDK_REBUILD: 'false'

permissions:
  contents: read

jobs:
  validation-build-mtl:
    runs-on: [self-hosted, linux, x64, dpdk]
    timeout-minutes: 60
    outputs:
      pipenv-activate: ${{ steps.pipenv-install.outputs.VIRTUAL_ENV }}
    steps:
      - name: 'preparation: Harden Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: 'preparation: Clean workspace and checkout MTL'
        uses: OpenVisualCloud/Media-Transport-Library/.github/actions/checkout-clean@2f540b33d05ab93541c816182b791c0fb6b5d143
        with:
          ref: '${{ inputs.branch-to-checkout }}'

      - name: Validate host and restore dependency caches
        uses: ./.github/actions/validate-host

      - name: 'preparation: Print TEST_ environment'
        if: always()
        run: task ci:validation -- print-environment

      - name: 'preparation: Checkout DPDK'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: env.DPDK_REBUILD == 'true'
        with:
          repository: 'DPDK/dpdk'
          ref: 'v${{  env.DPDK_VERSION  }}'
          path: 'dpdk'

      - name: 'configuration: Verify the build dependencies'
        run: task ci:validation -- verify-dependencies

      - name: 'configuration: Apply dpdk patches'
        if: env.DPDK_REBUILD == 'true'
        run: task ci:validation -- patch-dpdk

      - name: 'installation: Build dpdk'
        if: env.DPDK_REBUILD == 'true'
        run: task ci:validation -- build-dpdk

      - name: 'installation: Build mtl'
        run: task ci:validation -- build-mtl

      - name: 'preparation: Verify pipenv environment'
        working-directory: tests/acceptance
        id: pipenv-install
        run: task ci:validation -- verify-pipenv

  # Timeout of this job is set to 12h [60m/h*12h=720m]
  validation-run-tests:
    needs: [validation-build-mtl]
    runs-on: [self-hosted, linux, x64, dpdk]
    timeout-minutes: 720
    env:
      PYTEST_ALIAS: 'sudo --preserve-env python3 -m pipenv run pytest'
      PYTEST_PARAMS: '--media=/mnt/media --build="../.."'
      PYTEST_RETRIES: '3'
    steps:
      - name: 'preparation: Harden Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: 'preparation: Evaluate choosen validation-test-port-p and validation-test-port-r'
        env:
          PORT_P_NAME: ${{ inputs.validation-test-port-p }}
          PORT_R_NAME: ${{ inputs.validation-test-port-r }}
        run: task ci:validation -- select-ports

      - uses: ./.github/actions/cleanup
      - name: 'preparation: Binding network adapter pf to kernel driver'
        if: inputs.validation-iface-binding != 'bind_pmd'
        run: task ci:validation -- bind-kernel

      - name: 'preparation: Binding network adapter ${{ inputs.validation-iface-binding }}'
        env:
          VALIDATION_IFACE_BINDING: ${{ inputs.validation-iface-binding }}
        run: task ci:validation -- bind-interface

      - name: 'execution: Run validation-bare-metal tests in pipenv environment'
        working-directory: tests/acceptance
        run: task ci:validation -- run-tests
        env:
          TEST_PORT_P: ${{ env.TEST_PORT_P }}
          TEST_PORT_R: ${{ env.TEST_PORT_R }}
          PYTEST_RETRIES: '3'
          VALIDATION_TESTS_1: ${{ inputs.validation-tests-1 }}
          VALIDATION_TESTS_2: ${{ inputs.validation-tests-2 }}
          VALIDATION_NO_FAIL_TESTS: ${{ inputs.validation-no-fail-tests }}

      - name: 'execution: Run validation-pre-release-1 in pipenv environment'
        if: inputs.validation-pre-release-1 != 'NONE'
        working-directory: tests/acceptance
        env:
          VALIDATION_PRERELEASE: ${{ inputs.validation-pre-release-1 }}
        run: task ci:validation -- prerelease

      - name: 'execution: Run validation-pre-release-2 in pipenv environment'
        if: inputs.validation-pre-release-2 != 'NONE'
        working-directory: tests/acceptance
        env:
          VALIDATION_PRERELEASE: ${{ inputs.validation-pre-release-2 }}
        run: task ci:validation -- prerelease

      - name: 'execution: Run validation-pre-release-3 in pipenv environment'
        if: inputs.validation-pre-release-3 != 'NONE'
        working-directory: tests/acceptance
        env:
          VALIDATION_PRERELEASE: ${{ inputs.validation-pre-release-3 }}
        run: task ci:validation -- prerelease

      - uses: ./.github/actions/cleanup
      - name: 'cleanup: Create archive with logs from execution'
        if: always()
        working-directory: tests/acceptance
        run: task ci:validation -- archive-logs

      - name: 'cleanup: Restore valid owner to repository and directories'
        if: always()
        run: task ci:validation -- restore-owner

      - name: 'cleanup: Bind pf to kernel driver'
        if: always()
        run: task ci:validation -- bind-kernel

      - name: 'cleanup: Validation execution logs'
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: 'validation-execution-logs.tar.gz'
          path: '${{ github.workspace }}/tests/acceptance/validation-execution-logs.tar.gz'

      - name: 'cleanup: Generate runner summary'
        if: always()
        env:
          RUNNER_NAME: ${{ runner.name }}
        run: task ci:validation -- summary
