name: Windows build

on:
  push:
    paths:
      - 'include/**'
      - 'lib/**'
      - 'patches/dpdk/**'
      - script/build_dpdk.sh
      - 'tests/**'
      - build.sh
      - kahawai.json
      - meson.build
      - meson_options.txt
      - VERSION
      - .github/workflows/ubuntu_build_with_gtest.yml
  pull_request:
    paths:
      - 'include/**'
      - 'lib/**'
      - 'patches/dpdk/**'
      - script/build_dpdk.sh
      - 'tests/**'
      - build.sh
      - kahawai.json
      - meson.build
      - meson_options.txt
      - VERSION
      - .github/workflows/ubuntu_build_with_gtest.yml

env:
  # Customize the env if
  BUILD_TYPE: Release
  DPDK_VERSION: 22.07

jobs:
  Build:
    #if: github.repository == 'OpenVisualCloud/Media-Transport-Library'
    runs-on: [Windows, self-hosted]

    steps:
    - name: checkout kahawai repo
      uses: actions/checkout@v3
    
    - name: Build
      run: C:\actions-runner\windows_installer.ps1
      
