name: Windows build

on: [push, pull_request]

env:
  # Customize the env if
  BUILD_TYPE: Release
  DPDK_VERSION: 22.07

jobs:
  Build:
    if: github.repository == 'OpenVisualCloud/Media-Transport-Library'
    runs-on: [Windows, self-hosted]

    steps:
    - name: checkout kahawai repo
      uses: actions/checkout@v3
    
    - name: Build
      run: C:\actions-runner\windows_installer.ps1
      
